name: Cross-compile Corretto 21 for Windows

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Corretto repository
      uses: actions/checkout@v4
      with:
        repository: corretto/corretto-21
        ref: lilliput-2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf build-essential libx11-dev libxext-dev libxrender-dev libxrandr-dev libxtst-dev libxt-dev libcups2-dev libfontconfig1-dev libasound2-dev mingw-w64

    - name: Install boot JDK (Corretto 20)
      run: |
        wget https://corretto.aws/downloads/latest/amazon-corretto-20-x64-linux-jdk.tar.gz -O amazon-corretto-20-x64-linux-jdk.tar.gz
        tar -xzf amazon-corretto-20-x64-linux-jdk.tar.gz
        echo "BOOT_JDK=$PWD/$(ls -d amazon-corretto-20*linux-x64)" >> $GITHUB_ENV

    - name: (FIX) Create dummy cygpath and wslpath to satisfy configure script
      run: |
        mkdir -p $HOME/bin
        echo -e '#!/bin/sh\necho "$@"' | tee $HOME/bin/cygpath > /dev/null
        chmod +x $HOME/bin/cygpath
        ln -s $HOME/bin/cygpath $HOME/bin/wslpath
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Configure the build for Windows cross-compilation
      run: |
        bash ./configure --with-boot-jdk=${{ env.BOOT_JDK }} \
                        --openjdk-target=x86_64-w64-mingw32 \
                        --with-toolchain-type=gcc

    - name: Build Corretto
      run: make images

    - name: Archive the build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: corretto-21-windows-x64
        path: build/windows-x86_64-server-release/images/jdk
