name: Build Corretto 21 on Windows using WSL

on:
    workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: lilliput-2
    - name: Install dependencies in WSL
      run: |
        wsl sudo apt-get update
        wsl sudo apt-get install -y autoconf make gcc g++ libX11-dev libXext-dev libXrender-dev libXtst-dev libXt-dev libasound2-dev libcups2-dev libfontconfig1-dev openjdk-17-jdk
    - name: Configure and build in WSL
      run: |
        wsl bash -c "cd $(wslpath '$GITHUB_WORKSPACE') && bash configure --with-debug-level=release --with-target-bits=64 && make"
    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: corretto-21-lilliput-2
        path: ${{ github.workspace }}/build/linux-x86_64-normal-server-release
