name: Build Celeritas

on:
  workflow_dispatch:
    inputs:
      minecraft_version:
        description: 'Minecraft Version to Build'
        required: true
        type: choice
        options:
          - 1.21.1
          - 1.20.4
          - 1.20.1
          - 1.19.2
          - 1.18.2
          - 1.16.5
          - 1.17.10
          - 1.12.2
          - 1.10.2
          - 1.7.10
          - 1.2.5
          - 1.0.0-beta.7.3
          - 1.0.0-beta.8.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        run: git clone https://git.taumc.org/embeddedt/celeritas.git .
        shell: pwsh
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -Ptarget_versions="${{ github.event.inputs.minecraft_version }}" packageJar

      - name: List files in build directory
        run: ls -R build

      - name: Determine artifact path
        id: get_artifact_path
        run: |
          mc_version="${{ github.event.inputs.minecraft_version }}"
          artifact_path=""
          if [[ "$mc_version" == "1.12.2" || "$mc_version" == "1.10.2" ]]; then
            artifact_path="forge122/build/libs/*[!dev].jar"
          elif [[ "$mc_version" == "1.2.5" || "$mc_version" == "1.0.0-beta.7.3" || "$mc_version" == "1.0.0-beta.8.1" ]]; then
            artifact_path="babric/build/libs/*[!dev].jar"
          elif [[ "$mc_version" == "1.7.10" ]]; then
            artifact_path="forge1710/build/libs/*[!dev].jar"
          else
            artifact_path="modern/build/libs/*[!dev].jar"
          fi
          echo "path=${artifact_path}" >> $GITHUB_OUTPUT

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-${{ github.event.inputs.minecraft_version }}
          path: ${{ steps.get_artifact_path.outputs.path }}
