name: Cross-compile Corretto 21 for Windows from WSL

on:
  push:
    branches:
      - main # Or any other branch you want to trigger the build from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Corretto source code
      uses: actions/checkout@v4
      with:
        repository: corretto/corretto-21
        ref: lilliput-2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf make zip unzip build-essential

    - name: Download Windows Boot JDK
    - uses: actions/setup-java@v4
      with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'


    - name: Configure the build
      run: |
        bash configure --with-boot-jdk=/opt/boot-jdk

    - name: Build Corretto
      run: |
        make images

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: corretto-21-windows
        path: build/*/images/jdk
