name: Build Celeritas

on:
  workflow_dispatch:
    inputs:
      minecraft_version:
        description: 'Minecraft version to build for'
        required: true
        type: choice
        options:
          - '1.21.1'
          - '1.20.6'
          - '1.20.4'
          - '1.20.1'
          - '1.19.4'
          - '1.19.2'
          - '1.18.2'
          - '1.17.1'
          - '1.16.5'
          - '1.15.2'
          - '1.14.4'
          - '1.13.2'
          - '1.12.2'
          - '1.11.2'
          - '1.10.2'
          - '1.9.4'
          - '1.8.9'
          - '1.7.10'
          - '1.2.5'
          - 'all'
        default: '1.20.1'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone repository
      run: git clone https://git.taumc.org/embeddedt/celeritas.git .
      shell: pwsh
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'graalvm'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: false
    
    - name: Cache build outputs
      uses: actions/cache@v4
      with:
        path: |
          build/
          .gradle/
          versions/*/build/
        key: ${{ runner.os }}-celeritas-build-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle.properties', 'stonecutter.gradle.kts') }}-${{ github.event.inputs.minecraft_version }}
        restore-keys: |
          ${{ runner.os }}-celeritas-build-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle.properties', 'stonecutter.gradle.kts') }}-all
          ${{ runner.os }}-celeritas-build-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', 'gradle.properties', 'stonecutter.gradle.kts') }}-
          ${{ runner.os }}-celeritas-build-
      
    - name: Build for specific version
      if: ${{ github.event.inputs.minecraft_version != 'all' }}
      run: ./gradlew -Ptarget_versions="${{ github.event.inputs.minecraft_version }}" packageJar
      
    - name: Build for all versions
      if: ${{ github.event.inputs.minecraft_version == 'all' }}
      run: ./gradlew packageJar
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: celeritas-${{ github.event.inputs.minecraft_version }}-${{ github.run_number }}
        path: build/libs/**/*.jar
        if-no-files-found: error
