name: Build Celeritas

on:
  workflow_dispatch:
    inputs:
      minecraft_version:
        description: 'Minecraft Version to Build'
        required: true
        type: choice
        options:
          - 1.21.1
          - 1.20.4
          - 1.20.1
          - 1.19.2
          - 1.18.2
          - 1.16.5
          - 1.17.10
          - 1.12.2
          - 1.10.2
          - 1.7.10
          - 1.2.5
          - 1.0.0-beta.7.3
          - 1.0.0-beta.8.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -Ptarget_versions="${{ github.event.inputs.minecraft_version }}" packageJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celeritas-${{ github.event.inputs.minecraft_version }}
          path: '**/build/libs/*.jar'
