name: Build Corretto 21 on Windows using WSL

on:
    workflow_dispatch: 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: corretto/corretto-21
        ref: lilliput-2
    - name: Install dependencies in WSL
      run: |
        Invoke-WebRequest -Uri https://aka.ms/wslubuntu -OutFile Ubuntu.appx -UseBasicParsing
        tar -tf .\Ubuntu.appx
        mkdir "$env:USERPROFILE\AppData\Local\DebianWSL" | Out-Null
        tar -xf .\Ubuntu_2204.1.7.0_x64.appx -C $"env:USERPROFILE\AppData\Local\DebianWSL"
        $userenv = [System.Environment]::GetEnvironmentVariable("Path", "User")
        [System.Environment]::SetEnvironmentVariable("PATH", $userenv + ";$env:USERPROFILE\AppData\Local\UbuntuWSL", "User")  
        ubuntu.exe sudo apt-get update
        ubuntu.exe sudo apt-get install -y autoconf make gcc g++ libX11-dev libXext-dev libXrender-dev libXtst-dev libXt-dev libasound2-dev libcups2-dev libfontconfig1-dev openjdk-17-jdk
    - name: Configure and build in WSL
      run: |
        ubuntu.exe bash -c "cd $(wslpath '$GITHUB_WORKSPACE') && bash configure --with-debug-level=release --with-target-bits=64 && make"
    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: corretto-21-lilliput-2
        path: ${{ github.workspace }}/build/linux-x86_64-normal-server-release
