name: Cross-compile Corretto 21 for Windows from WSL

on:
  push:
    branches:
      - main # Or any other branch you want to trigger the build from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Corretto source code
      uses: actions/checkout@v3
      with:
        repository: corretto/corretto-21
        ref: lilliput-2

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf make zip unzip build-essential

    - name: Download Windows Boot JDK
      run: |
        wget -O boot-jdk.zip https://corretto.aws/downloads/latest/amazon-corretto-21-x64-windows-jdk.zip
        unzip boot-jdk.zip -d boot-jdk
        # The actual path to the JDK might be nested inside the unzipped folder
        # We'll find it and move it to a known location
        JDK_PATH=$(find boot-jdk -name "jdk*" -type d | head -n 1)
        mv $JDK_PATH /opt/boot-jdk


    - name: Configure the build
      run: |
        bash configure --with-boot-jdk=/opt/boot-jdk

    - name: Build Corretto
      run: |
        make images

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: corretto-21-windows
        path: build/*/images/jdk
