name: Cross-compile Corretto 21 for Windows from WSL

on:
  push:
    branches:
      - main # Or any other branch you want to trigger the build from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Corretto source code
      uses: actions/checkout@v4
      with:
        repository: corretto/corretto-21
        ref: lilliput-2

    - name: Setup Java for the build environment
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin'
          java-version: '21'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf make zip unzip build-essential wget

    # Definitive fix for the Windows Boot JDK setup
    - name: Download and setup Windows Boot JDK
      run: |
        # Download the JDK
        wget -O boot-jdk.zip https://corretto.aws/downloads/latest/amazon-corretto-21-x64-windows-jdk.zip
        
        # Unzip to a temporary directory
        unzip -q boot-jdk.zip -d boot-jdk-unzipped
        
        # For debugging: List the contents to see the actual folder name
        echo "Contents of boot-jdk-unzipped:"
        ls -l boot-jdk-unzipped
        
        # Find the full path of the single directory inside the unzipped folder
        JDK_DIR_PATH=$(find boot-jdk-unzipped -maxdepth 1 -mindepth 1 -type d)
        
        # Move that found directory to be /opt/boot-jdk. This is a rename, not moving *into*.
        sudo mv "$JDK_DIR_PATH" /opt/boot-jdk
        
        # Final verification that should now succeed
        echo "Verifying /opt/boot-jdk/bin/java exists:"
        ls -l /opt/boot-jdk/bin/java

    - name: Configure the build for cross-compilation
      run: |
        # Explicitly define the build, host, and target platforms for clarity
        bash configure --with-boot-jdk=/opt/boot-jdk \
                       --with-toolchain-variant=x86_64-w64-mingw32 \
                       --with-target-bits=64 \
                       --with-jvm-variants=server
    
    - name: Build Corretto
      run: |
        make images

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: corretto-21-windows
        path: build/linux-x86_64-server-release/images/jdk
