name: Cross-compile Corretto 21 for Windows from WSL

on:
  push:
    branches:
      - main # Or any other branch you want to trigger the build from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Corretto source code
      uses: actions/checkout@v4
      with:
        repository: corretto/corretto-21
        ref: lilliput-2

    - name: Setup Java for the build environment
      uses: actions/setup-java@v4
      with:
          distribution: 'temurin'
          java-version: '21'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf make zip unzip build-essential wget

    # This is the crucial step to fix the error
    - name: Download and setup Windows Boot JDK
      run: |
        wget -O boot-jdk.zip https://corretto.aws/downloads/latest/amazon-corretto-21-x64-windows-jdk.zip
        unzip -q boot-jdk.zip -d boot-jdk-unzipped
        # Find the actual JDK directory, as it's often nested
        JDK_PATH=$(find boot-jdk-unzipped -name "jdk*" -type d | head -n 1)
        sudo mv $JDK_PATH /opt/boot-jdk

    - name: Configure the build for cross-compilation
      run: |
        bash configure --with-boot-jdk=/opt/boot-jdk --with-target-bits=64 --with-jvm-variants=server
    
    - name: Build Corretto
      run: |
        make images

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: corretto-21-windows
        path: build/linux-x86_64-server-release/images/jdk
