name: Build Folia

on:
  workflow_dispatch:
    inputs:
      minecraft_version:
        description: Minecraft version
        required: true
        type: choice 
        options:
        -  '1.21.8'
        -  '1.21.7'
        -  '1.21.6'
        -  '1.21.5'
        -  '1.21.4'
        default: '1.21.8'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
        with:
          repository: "PaperMC/Folia"
          ref: ver/${{ github.event.inputs.minecraft_version }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyAllPatches --stacktrace
      - name: Build
        run: |
          ./gradlew build
          ls
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: folia-${{ github.event.choice.minecraft_version }}
          path: paper-server/build/libs
