name: tests lmarena

on:
  schedule:
    - cron: '0 5 * * 1'  # 8:00 Moscow time (UTC+3)
  workflow_dispatch:

env:
  UPSTREAM_REPO: corretto/corretto-21
  UPSTREAM_BRANCH: lilliput-2
  VAR_NAME: LAST_BUILT_SHA
  CORRETTO_DIR: corretto-source
  MSYS2_PACKAGES: make coreutils diffutils binutils zip unzip autoconf automake

jobs:
  check-sha:
    runs-on: ubuntu-latest
    outputs:
      needs_build: ${{ steps.check.outputs.needs_build }}
      current_sha: ${{ steps.get-sha.outputs.current_sha }}
    steps:
      - name: Get last built SHA
        id: get-var
        run: |
          echo "last_sha=$(gh variable get $VAR_NAME --repo $GITHUB_REPOSITORY 2>/dev/null || echo '')" >> $GITHUB_OUTPUT
        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.UPSTREAM_REPO }}
          ref: ${{ env.UPSTREAM_BRANCH }}
          fetch-depth: 1
          path: ${{ env.CORRETTO_DIR }}
        
      - name: Get current SHA
        id: get-sha
        run: |
          current_sha=$(cd $CORRETTO_DIR && git rev-parse HEAD)
          echo "current_sha=$current_sha" >> $GITHUB_OUTPUT
        
      - name: Check build condition
        id: check
        run: |
          last_sha="${{ steps.get-var.outputs.last_sha }}"
          current_sha="${{ steps.get-sha.outputs.current_sha }}"
          if [[ "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            echo "needs_build=true" >> $GITHUB_OUTPUT
          elif [[ -z "$last_sha" || "$last_sha" != "$current_sha" ]]; then
            echo "needs_build=true" >> $GITHUB_OUTPUT
          else
            echo "needs_build=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: check-sha
    if: ${{ needs.check-sha.outputs.needs_build == 'true' }}
    runs-on: windows-latest
    permissions:
      contents: read
      actions: write
    steps:
      - name: Update LAST_BUILT_SHA
        run: |
          gh variable set $VAR_NAME --body ${{ needs.check-sha.outputs.current_sha }} --repo $GITHUB_REPOSITORY
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout source
        uses: actions/checkout@v4
        with:
          repository: ${{ env.UPSTREAM_REPO }}
          ref: ${{ env.UPSTREAM_BRANCH }}
          path: ${{ env.CORRETTO_DIR }}
          fetch-depth: 1

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            make
            coreutils
            diffutils
            binutils
            zip
            unzip
            autoconf
            automake
          cache-key: msys2-${{ hashFiles('.msys2_packages') }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          architecture: x64

      - name: Configure build
        shell: msys2 {0}
        working-directory: ${{ env.CORRETTO_DIR }}
        run: |
          boot_jdk=$(cygpath -u "$JAVA_HOME")
          ./configure --with-boot-jdk="$boot_jdk" \
            --disable-warnings-as-errors \
            --with-debug-level=release

      - name: Build JDK
        shell: msys2 {0}
        working-directory: ${{ env.CORRETTO_DIR }}
        run: |
          make -j$(nproc) images

      - name: Clean debug symbols
        shell: pwsh
        run: |
          $jdkPath = Get-ChildItem ".\corretto-source\build\*\images\jdk" -Directory | Select-Object -First 1
          Get-ChildItem -Path $jdkPath.FullName -Recurse -Include "*.pdb", "*.map" | Remove-Item -Force

      - name: Prepare artifact
        shell: pwsh
        run: |
          $jdkPath = Get-ChildItem ".\corretto-source\build\*\images\jdk" -Directory | Select-Object -First 1
          $version = (Get-Content "$jdkPath\release" | Slosh -Pattern 'JAVA_VERSION="(?<version>.)"').version
          $artifactPath = Join-Path $env:GITHUB_WORKSPACE "corretto-21-lilliput-$version-windows"
          New-Item -ItemType Directory -Path $artifactPath
          Move-Item -Path "$jdkPath\*" -Destination $artifactPath

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: corretto-21-lilliput-windows-${{ github.run_id }}
          path: corretto-21-lilliput-*-windows/
          retention-days: 7
